import { defineStore } from 'pinia'

export const usePlayerStore =
    defineStore({
        id: 'player',
        state: () => ({
            playerId: 'Player One',
            playerLevel: 1,
            playerStartingHealth: 100,
            playerHealth: 100,
            coinOnHand: 1000,
            playerAttack: 1,
            playerDefense: 1,
            playerStrength: 1,

            playerQuests: [],
            playerEquipped: {
                player_helm:{
                    id: 'helm',
                    itemSlot: 'player_helm',
                    name: '',
                    description: '',
                    value: '',
                    price: '',
                    imageSrc: require('../assets/images/placeholders/helm.png'),
                },
                player_armor:{
                    id: 'armor',
                    itemSlot: 'player_armor',
                    name: '',
                    description: '',
                    value: '',
                    price: '',
                    imageSrc: require('../assets/images/placeholders/armor.png'),
                },
                player_shield:{
                    id: 'shield',
                    itemSlot: 'player_shield',
                    name: '',
                    description: '',
                    value: '',
                    price: '',
                    imageSrc: require('../assets/images/placeholders/shield.png'),
                },
                player_gloves:{
                    id: 'gloves',
                    itemSlot: 'player_gloves',
                    name: '',
                    description: '',
                    value: '',
                    price: '',
                    imageSrc: require('../assets/images/placeholders/gloves.png'),
                },
                player_vambraces:{
                    id: 'vambraces',
                    itemSlot: 'player_vambraces',
                    name: '',
                    description: '',
                    value: '',
                    price: '',
                    imageSrc: require('../assets/images/placeholders/vambraces.png'),
                },
                player_sword:{
                    id: 'sword',
                    itemSlot: 'player_sword',
                    name: '',
                    description: '',
                    value: '',
                    price: '',
                    imageSrc: require('../assets/images/placeholders/sword.png'),
                },
                player_boots:{
                    id: 'boots',
                    itemSlot: 'player_boots',
                    name: '',
                    description: '',
                    value: '',
                    price: '',
                    imageSrc: require('../assets/images/placeholders/boots.png'),
                },
                player_necklace:{
                    id: 'necklace',
                    itemSlot: 'player_necklace',
                    name: '',
                    description: '',
                    value: '',
                    price: '',
                    imageSrc: require('../assets/images/placeholders/necklace.png'),
                },
                player_ring:{
                    id: 'ring',
                    itemSlot: 'player_ring',
                    name: '',
                    description: '',
                    value: '',
                    price: '',
                    imageSrc: require('../assets/images/placeholders/ring.png'),
                },
                player_belt:{
                    id: 'belt',
                    itemSlot: 'player_belt',
                    name: '',
                    description: '',
                    value: '',
                    price: '',
                    imageSrc: require('../assets/images/placeholders/belt.png'),
                },
            },
            playerPacked: [],

            horseInventory: [
                {
                    id: 'shoes',
                    itemSlot: 'horse_shoes',
                    name: 'shoes',
                    description: "",
                    value: '',
                    price: '',
                    imageSrc: require('../assets/images/placeholders/horseshoes.png'),            
                },
                {
                    id: 'saddle',
                    itemSlot: 'horse_saddle',
                    name: 'saddle',            
                    description: "",
                    value: '',
                    price: '',
                    imageSrc: require('../assets/images/placeholders/saddle.png'),            
                },
                {
                    id: 'bag',
                    itemSlot: 'horse_bag',
                    name: 'bag',
                    description: "",
                    value: '',
                    price: '',
                    imageSrc: require('../assets/images/placeholders/bags.png'),        
                },
            ],

            nextLevel: 100,
            increase: 3,
            playerXP: 0,
            playerTotalXP: 0,
            healthPerSec: 0,
        })
    })