import { defineStore } from 'pinia'

export const useQuestStore =
    defineStore({
        id: 'quest',
        state: () => ({
            quests: [
                {
                    id: 'matildaQuest',
                    title: 'Prove Yourself to Matilda',
                    active: false,
                    complete: false,
                    description: "Bring Matilda the Mage three Sacred Spores from the Mushroom Spirits of the Black Forest.",
                    need: "Sacred Spores",
                    // need: "Basic Healing Draught",
                    qty: 3,
                    largeIcon: require('../assets/images/village_school/school_teacher.png'),
                    smallIcon: require('../assets/images/forest/forest_monster_1_treasure.png'),
                    questPoints: 10,
                    playerXP: 10,
                    coins: 0,
                    reward: "Gain permission to enroll in Matilda's School of Magic.",
                    rewardScript: "permission to enroll in my School of Magic."
                },
                {
                    id: 'guildCollectSeven',
                    title: 'Collect a small token from each of the hunting grounds',
                    active: false,
                    complete: false,
                    description: "Collect a Sand Crab Shell, some Sacred Spores, a Rotten Femur, a piece of Bat Leather, a Fae Light, a set of Goblin Ears, and some Tangled Rootbeast Vines",
                    need: "Sand Crab Shell",
                    qty: 1,
                    need2: "Sacred Spores",
                    qty2: 1,
                    need3: "Rotten Femur",
                    qty3: 1,
                    need4: "Bat Leather",
                    qty4: 1,
                    need5: "Fae Light",
                    qty5: 1,
                    need6: "Goblin Ears",
                    qty6: 1,
                    need7: "Tangled Rootbeast Vines",
                    qty7: 1,
                    largeIcon: require('../assets/images/village_guild/The_Guildmaster.png'),
                    smallIcon: require('../assets/images/forest/forest_monster_1_treasure.png'),
                    questPoints: 20,
                    playerXP: 15,
                    coins: 2000,
                    reward: "2000 coins.",
                    rewardScript: "your reward of 2000 coins, and the repect of the Guild."
                },
                {
                    id: 'drunkardQuest1',
                    title: "Help the village drunk prove they're right",
                    active: false,
                    complete: false,
                    description: "Collect three Sand Crab Shells to help prove that the Firesand Desert is actually an ocean in disguise.",
                    need: "Sand Crab Shell",
                    qty: 3,
                    largeIcon: require('../assets/images/quests/Pub_drunkard.png'),
                    smallIcon: require('../assets/images/desert/desert_monster_1_treasure.png'),
                    questPoints: 10,
                    playerXP: 0,
                    coins: 0,
                    reward: "Gain the respect of the village drunk.",
                    rewardScript: "300 coins and my *hic* ... my respect!  "
                },
                {
                    id: 'barkeepQuest1',
                    title: "Discretion is the key.",
                    active: false,
                    complete: false,
                    description: "Purchase a Ring of Vigor to help the barkeep help his friend and help you out in the process.",
                    need: "Enchanted Ring of Vigor",
                    qty: 1,
                    largeIcon: require('../assets/images/quests/Pub_barkeep.png'),
                    smallIcon: require('../assets/images/village_oddities/Oddities_enchanted_ring_1.png'),
                    questPoints: 25,
                    playerXP: 200,
                    coins: 3500,
                    reward: "Gain the attention and gratitude of the Guild.",
                    rewardScript: "3000 coins for the ring, 500 coins for our thanks, and the gratitude of the Guild."
                },


            ],
        }),
        actions: {},
    })