import { defineStore } from 'pinia'

export const useShopStore =
    defineStore({
        id: 'shops',
        state: () => ({
            playerId: 'Player One',
            apothecary: [
                {
                    id: 'apo_health_1',
                    // id: Math.floor(Math.random() * 10000)
                    // note: this works to generate a random#, but it only does it once.  how to generate a new # with each sale?
                    itemSlot: 'null',
                    itemUse: 'healing',
                    itemShop: 'Apothecary',
                    name: 'Simple Healing Draught',                    
                    description: 'A simple brew that will perk you up a bit.',
                    value: '+10 health',
                    attack: 0,
                    defense: 0,
                    strength: 0,
                    life: 10,
                    mana: 0, 
                    intelligence: 0,
                    price: 10,
                    imageSrc: require('../assets/images/village/Apothecary_clay_bottle_1.png'),                    
                },
                {
                    id: 'apo_strength_1',
                    itemSlot: 'null',
                    itemUse: 'strength',
                    itesmShop: 'Apothecary',
                    name: 'Tincure of Strength',
                    description:"Rub this in and you'll instantly feel stronger, for one battle anyway.",
                    value: '+3 strength',
                    attack: 0,
                    defense: 0,
                    strength: 5,
                    life: 0,
                    price: 500,
                    imageSrc: require('../assets/images/village/Apothecary_clay_jar_1.png'),                    
                },
                {
                    id: 'apo_poison_1',
                    itemSlot: 'null',
                    itemUse: 'poison',
                    itemShop: 'Apothecary',
                    name: 'Simple Anti-venom Potion',
                    description:'You would not believe the number of things that are poisonous out there',
                    value: 'cures you of poisoning, lasts until next exposure',
                    attack: 0,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    price: 350,
                    imageSrc: require('../assets/images/village/Apothecary_potions_bottle_1.png'),                    
                },
                {
                    id: 'apo_soup_1',
                    itemSlot: 'null',
                    itemUse: 'multi',
                    itemShop: 'Apothecary',
                    name: 'Bone Broth Soup',
                    description: "I know how it looks.  Just give it a try - I think you'll like it!",
                    value: '+5-15 health and +1-10 strength',
                    attack: 0,
                    defense: 0,
                    strength: Math.floor(Math.random()*(10 - 1)) + 1,
                    life: Math.floor(Math.random()*(15 - 5)) + 5,
                    price: 3500,
                    imageSrc: require('../assets/images/village/Apothecary_soup_1.png'),                    
                },
            ],
            armory: [
                {
                    id: 'arm_leath_armor_1',
                    itemSlot: 'player_armor',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Basic Leather Armor',
                    description: 'Cheap, reliable, and sturdy',
                    value: '+10 defense',
                    attack: 0,
                    defense: 10,
                    strength: 0,
                    life: 0,
                    price: 200,
                    imageSrc: require('../assets/images/village/Armory_leather_armor_1.png'),
                },
                {
                    id: 'arm_leath_gauntlet_1',
                    itemSlot: 'player_gloves',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Leather Gauntlets',
                    description:"Just the thing to help you keep a strong grip on your sword.",
                    value: '+3 defense',
                    attack: 0,
                    defense: 3,
                    strength: 0,
                    life: 0,
                    price: 100,
                    imageSrc: require('../assets/images/village/Armory_leather_gauntlets_1.png'),
                },
                {
                    id: 'arm_leather_boots_1',
                    itemSlot: 'player_boots',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Sturdy Leather Boots',
                    description:'Hunting monsters with bad boots is a bad idea.  You need good footwear.',
                    value: '+3 defense and +2 strength',
                    attack: 0,
                    defense: 3,
                    strength: 2,
                    life: 0,
                    price: 150,
                    imageSrc: require('../assets/images/village/Armory_leather_boots_1.png'),
                },
                {
                    id: 'arm_enchant_boots_1',
                    itemSlot: 'player_boots',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Enchanted Boots',
                    description: "A gift from a friendly 'Shroom Spirit, these are great if you're considering adding magic items to your armor",
                    value: '+1-5 defense, and poison resistance, and occasional +1-5 health',
                    attack: 0,
                    defense: 3,
                    strength: 0,
                    life: 5,
                    price: 350,
                    imageSrc: require('../assets/images/village/Armory_enchanted_boots_1.png'),
                },
            ],
            blacksmith: [
                {
                    id: 'smith_sword_1',
                    itemSlot: 'player_sword',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Basic Steel Sword',
                    description: 'A good sword to start out with',
                    value: '+5 attack',
                    attack: 5,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    price: 150,
                    imageSrc: require('../assets/images/village/Blacksmith_sword_1.png'),
                  },
                  {
                    id: 'smith_helm_1',
                    itemSlot: 'player_helm',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Metal Helmet',
                    description:"Some basic head protection.  You're going to want it.",
                    value: '+3 defense',
                    attack: 0,
                    defense: 3,
                    strength: 0,
                    life: 0,
                    price: 150,
                    imageSrc: require('../assets/images/village/Blacksmith_helmet_1.png'),                    
                  },
                  {
                    id: 'smith_shield_1',
                    itemSlot: 'player_shield', 
                    itemUse: 'null',
                    itemShop: 'Blacksmith',                   
                    name: 'Basic Wooden Shield',
                    description:"Won't help much against fire-based monsters, but useful against pretty much everything else.",
                    value: '+3 defense',
                    attack: 0,
                    defense: 3,
                    strength: 0,
                    life: 0,
                    price: 100,
                    imageSrc: require('../assets/images/village/Blacksmith_shield_1.png'),
                  },
                  {
                    id: 'smith_misc_1',
                    itemSlot: 'horse_shoes',  
                    itemUse: 'null', 
                    itemShop: 'Blacksmith',                 
                    name: 'Horseshoes',
                    description: "Everyone feels better with proper footware, horses included",
                    value: 'allows your horse to carry 10% more items',
                    carryBonus: 1,
                    price: 200,
                    imageSrc: require('../assets/images/village/Blacksmith_horseshoes_1.png'),
                  },
            ],
            oddities: [
                {
                    id: 'odd_ring_1',
                    itemSlot: 'player_ring',
                    itemUse: 'null',
                    itemShop: 'Oddities',
                    name: 'Enchanted Ring of Vigor',
                    description: 'Made by elves.  Good on the battlefield, and in the bedroom!',
                    value: '+4 attack',
                    attack: 4,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    price: 500,
                    imageSrc: require('../assets/images/village/Oddities_enchanted_ring_1.png'),
                  },
                  {
                    id: 'odd_skull_1',
                    itemSlot: 'null',
                    itemUse: 'null',
                    itemShop: 'Oddities',
                    name: 'Raven Skull',
                    description:"Useful for potions and spellwork.",
                    value: 'Potency results may vary',
                    price: 50,
                    imageSrc: require('../assets/images/village/Oddities_skull_1.png'),
                  },
                  {
                    id: 'odd_gloves_1',
                    itemSlot: 'player_gloves',
                    itemUse: 'null',
                    itemShop: 'Oddities',
                    name: 'Mysterious Leather Gloves',
                    description:"No telling what they do - but they're magic!",
                    value: '???',
                    attack: 0,
                    defense: 0,
                    strength: 0,
                    life: 10,
                    price: 750,
                    imageSrc: require('../assets/images/village/Oddities_enchanted_gloves_1.png'),
                  },
                  {
                    id: 'odd_herb_1',
                    itemSlot: 'null',
                    itemUse: 'null',
                    itemShop: 'Oddities',
                    name: "Mountain's Bane",
                    description: "A very rare herb of very potent magic",
                    value: 'Results vary by application',
                    price: 3000,
                    imageSrc: require('../assets/images/village/Oddities_herb_1.png'),
                  },
            ],

        }),
        actions: {
            getUniqueID() {
                this.id = (this.id + Math.ceil(Math.random()*1000000));
            }
        }
    })