import { defineStore } from 'pinia'

export const useShopStore =
    defineStore({
        id: 'shops',
        state: () => ({
            playerId: 'Player One',
            playerLevel: 1,
            apothecary: [ // note: will buy herbs, potions, and meats 
                {
                    id: 'apo_health_1',
                    // id: Math.floor(Math.random() * 10000)
                    // note: this works to generate a random#, but it only does it once.  how to generate a new # with each sale?
                    itemSlot: 'null',
                    itemUse: 'healing',
                    itemShop: 'Apothecary',
                    name: 'Basic Healing Draught',                    
                    description: 'A simple brew that will perk you up a bit.',
                    value: '+10 health',
                    attack: 0,
                    defense: 0,
                    strength: 0,
                    life: 10,
                    mana: 0, 
                    intelligence: 0,
                    price: 50,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_healing_1.png'),                    
                },
                {
                    id: 'apo_health_2',
                    itemSlot: 'null',
                    itemUse: 'healing',
                    itemShop: 'Apothecary',
                    name: 'Concentrated Healing Draught',                    
                    description: "A strong spirit that will reinvigorate you if you're feeling down.",
                    value: '+25 health',
                    attack: 0,
                    defense: 0,
                    strength: 0,
                    life: 25,
                    mana: 0, 
                    intelligence: 0,
                    price: 150,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_healing_2.png'),                    
                },
                {
                    id: 'apo_health_3',
                    itemSlot: 'null',
                    itemUse: 'healing',
                    itemShop: 'Apothecary',
                    name: 'Greater Healing Draught',                    
                    description: 'A potent cordial that will get you feeling much better',
                    value: '+50 health',
                    attack: 0,
                    defense: 0,
                    strength: 0,
                    life: 50,
                    mana: 0, 
                    intelligence: 0,
                    price: 300,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_healing_3.png'),                    
                },
                {
                    id: 'apo_health_4',
                    itemSlot: 'null',
                    itemUse: 'healing',
                    itemShop: 'Apothecary',
                    name: 'Blessed Healing Draught',                    
                    description: 'The strongest healing brew I make.  For most adventurers, it offers full healing.',
                    value: '+200 health',
                    attack: 0,
                    defense: 0,
                    strength: 0,
                    life: 200,
                    mana: 0, 
                    intelligence: 0,
                    price: 1000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_healing_4.png'),                    
                },
                {
                    id: 'apo_attack_1',
                    itemSlot: 'null',
                    itemUse: 'attacking',
                    itesmShop: 'Apothecary',
                    name: 'Energizing Tincure',
                    description:"Rub this in and you'll instantly feel the effects. Lasts for one battle",
                    value: '+5 attack',
                    attack: 5,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 500,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_attack_1.png'),                    
                },
                {
                    id: 'apo_attack_2',
                    itemSlot: 'null',
                    itemUse: 'attacking',
                    itesmShop: 'Apothecary',
                    name: 'Tincure of Motivation',
                    description:"Apply this potion and get what you need to succeed.  Lasts for one battle.",
                    value: '+10 attack',
                    attack: 10,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 1000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_attack_2.png'),                    
                },
                {
                    id: 'apo_attack_3',
                    itemSlot: 'null',
                    itemUse: 'attacking',
                    itesmShop: 'Apothecary',
                    name: 'Tincure of Inspiration',
                    description:"When applied, you'll aspire to greatness. Lasts for one battle",
                    value: '+25 attack',
                    attack: 25,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 1500,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_attack_3.png'),                    
                },
                {
                    id: 'apo_attack_4',
                    itemSlot: 'null',
                    itemUse: 'attack',
                    itesmShop: 'Apothecary',
                    name: 'Tincure of Vigor',
                    description:"Slather this on to gain a new energy toward life.  Effects are permanent!",
                    value: '+1 attack',
                    attack: 1,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 2000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_attack_4.png'),                    
                },
                {
                    id: 'apo_attack_5',
                    itemSlot: 'null',
                    itemUse: 'attack',
                    itesmShop: 'Apothecary',
                    name: 'Tincure of Ruthlessness',
                    description:"Douse yourself with this and see your enemies flee.  Effects are permanent!",
                    value: '+5 attack',
                    attack: 5,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 5000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_attack_5.png'),                    
                },
                {
                    id: 'apo_defense_1',
                    itemSlot: 'null',
                    itemUse: 'defending',
                    itemShop: 'Apothecary',
                    name: 'Small Shot Potion',
                    description:'Down this potion to gain a quick defense bonus.  Lasts for one battle.',
                    value: '+5 defense',
                    attack: 0,
                    defense: 5,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 350,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_defense_1.png'),                    
                },
                {
                    id: 'apo_defense_2',
                    itemSlot: 'null',
                    itemUse: 'defending',
                    itemShop: 'Apothecary',
                    name: "Defender's Doubleshot",
                    description:'Drink this to gain a good bit of defense power.  Lasts for one battle.',
                    value: '+15 defense',
                    attack: 0,
                    defense: 15,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 800,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_defense_2.png'),                    
                },
                {
                    id: 'apo_defense_3',
                    itemSlot: 'null',
                    itemUse: 'defense',
                    itemShop: 'Apothecary',
                    name: "Defender's Potion",
                    description:'Sip on this potion and gain a permanent defense bonus.',
                    value: '+1 defense',
                    attack: 0,
                    defense: 1,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 2000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_defense_3.png'),                    
                },
                {
                    id: 'apo_defense_4',
                    itemSlot: 'null',
                    itemUse: 'defense',
                    itemShop: 'Apothecary',
                    name: "Shell of Protection",
                    description:'Savor this potion.  The effects are permanent!',
                    value: '+5 defense',
                    attack: 0,
                    defense: 5,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 4000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_defense_4.png'),                    
                },
                {
                    id: 'apo_strength_1',
                    itemSlot: 'null',
                    itemUse: 'strengthening',
                    itemShop: 'Apothecary',
                    name: 'Strength Potion',
                    description:'Simple enough.  Drink this; get stronger.  Until you win your next battle, anyway.',
                    value: '+3 strength',
                    attack: 0,
                    defense: 0,
                    strength: 3,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 300,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_strength_1.png'),                    
                },
                {
                    id: 'apo_strength_2',
                    itemSlot: 'null',
                    itemUse: 'strengthening',
                    itemShop: 'Apothecary',
                    name: 'Hardiness Potion',
                    description:'Drink this and you can handle whatever comes!  Lasts for one battle.',
                    value: '+8 strength',
                    attack: 0,
                    defense: 0,
                    strength: 8,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 800,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_strength_2.png'),                    
                },
                {
                    id: 'apo_strength_3',
                    itemSlot: 'null',
                    itemUse: 'strength',
                    itemShop: 'Apothecary',
                    name: 'Potion of Brawn',
                    description:'This potion will permanently bulk you up!',
                    value: '+1 strength',
                    attack: 0,
                    defense: 0,
                    strength: 1,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 1300,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_strength_3.png'),                    
                },
                {
                    id: 'apo_strength_4',
                    itemSlot: 'null',
                    itemUse: 'strength',
                    itemShop: 'Apothecary',
                    name: 'Potion of Durability',
                    description:'Give it a try and see how much harder you can hit!  Effects are permanent.',
                    value: '+5 strength',
                    attack: 0,
                    defense: 0,
                    strength: 5,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 2000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_strength_4.png'),                    
                },
                {
                    id: 'apo_soup_1',
                    itemSlot: 'null',
                    itemUse: 'multi',
                    itemShop: 'Apothecary',
                    name: 'Bone Broth Soup',
                    description: "I know how it looks.  Just give it a try - I think you'll like it!",
                    value: '+3 health, +1 strength, fully charges mana',
                    attack: 0,
                    defense: 0,
                    strength: 1,
                    life: 3,
                    mana: 1,
                    intelligence: 0,
                    price: 2000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_soup_1.png'),                    
                },
                {
                    id: 'apo_soup_2',
                    itemSlot: 'null',
                    itemUse: 'multi',
                    itemShop: 'Apothecary',
                    name: 'Vegetable Soup',
                    description: "Full of vitamins and fiber - it's just what you need!",
                    value: '+3 health, +3 attack, fully charges mana',
                    attack: 3,
                    defense: 0,
                    strength: 0,
                    life: 3,
                    mana: 1,
                    intelligence: 0,
                    price: 4000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_soup_2.png'),                    
                },
                {
                    id: 'apo_soup_3',
                    itemSlot: 'null',
                    itemUse: 'multi',
                    itemShop: 'Apothecary',
                    name: 'Cream of Mushroom Soup',
                    description: "Made from freshly-foraged mushroom spirits, it'll perk you right up!",
                    value: '+3 health, +3 attack, +3 defense, fully charges mana',
                    attack: 3,
                    defense: 3,
                    strength: 0,
                    life: 3,
                    mana: 1,
                    intelligence: 0,
                    price: 6500,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_soup_3.png'),                    
                },
                {
                    id: 'apo_soup_4',
                    itemSlot: 'null',
                    itemUse: 'multi',
                    itemShop: 'Apothecary',
                    name: 'Chicken Noodle Soup',
                    description: "A classic for a reason - it's practically the perfect soup!",
                    value: '+8 health, +3 strength, +5 defense, fully charges mana',
                    attack: 0,
                    defense: 5,
                    strength: 3,
                    life: 8,
                    mana: 1,
                    intelligence: 0,
                    price: 8000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_soup_4.png'),                    
                },
                {
                    id: 'apo_soup_5',
                    itemSlot: 'null',
                    itemUse: 'multi',
                    itemShop: 'Apothecary',
                    name: 'Beef Stew',
                    description: "Hearty and filling - it'll warm you down to the soul!",
                    value: '+8 health, +3 strength, +5 attack, fully charges mana',
                    attack: 5,
                    defense: 0,
                    strength: 3,
                    life: 8,
                    mana: 1,
                    intelligence: 0,
                    price: 8000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_soup_5.png'),                    
                },
                {
                    id: 'apo_soup_6',
                    itemSlot: 'null',
                    itemUse: 'multi',
                    itemShop: 'Apothecary',
                    name: 'Spicy Curry Soup',
                    description: "The strongest, spiciest, wildest soup I can make!  Effects may vary.",
                    value: '+5-15 health, +1-5 attack, +1-5 defense, +1-5 strength, and fully charges mana',
                    attack: Math.floor(Math.random()*(10 - 1)) +1,
                    defense: Math.floor(Math.random()*(10 - 1)) + 1,
                    strength: Math.floor(Math.random()*(10 - 1)) + 1,
                    life: Math.floor(Math.random()*(15 - 5)) + 5,
                    mana: 1,
                    intelligence: 0,
                    price: 12000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_soup_6.png'),                    
                },
            ],
            armory: [  // note: will buy leathers, gems, scales, cloth-based items
                {
                    id: 'arm_belt_1',
                    itemSlot: 'player_belt',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Quicksilver Belt',
                    description: 'Enchanted belt that will improve your attacks.',
                    value: '+5-15 attack, +3-10 mana',
                    attack: Math.floor(Math.random()*(15 - 5)) +5,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: Math.floor(Math.random()*(10 - 3)) +3,
                    intelligence: 0,
                    price: 800,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_belt_1.png'),
                },
                {
                    id: 'arm_belt_2',
                    itemSlot: 'player_belt',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Belt of Lightening',
                    description: 'Enchanted belt made from captured lightning.',
                    value: '+10-30 attack, +5-20 mana',
                    attack: Math.floor(Math.random()*(30 - 10)) +10,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: Math.floor(Math.random()*(20 - 5)) +5,
                    intelligence: 0,
                    price: 2000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_belt_2.png'),
                },
                {
                    id: 'arm_belt_3',
                    itemSlot: 'player_belt',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Grey Wizard's Belt",
                    description: 'Enchanted using a spell from the great Grey Wizard themself.',
                    value: '+5-15 defense, +3-10 mana',
                    attack: 0,
                    defense: Math.floor(Math.random()*(15 - 5)) +5,
                    strength: 0,
                    life: 0,
                    mana: Math.floor(Math.random()*(10 - 3)) +3,
                    intelligence: 0,
                    price: 900,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_belt_3.png'),
                },
                {
                    id: 'arm_belt_4',
                    itemSlot: 'player_belt',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Templar's Belt",
                    description: 'Imported from the blessed Templar Monastery.',
                    value: '+10-30 defense, +5-20 mana',
                    attack: 0,
                    defense: Math.floor(Math.random()*(30 - 10)) +10,
                    strength: 0,
                    life: 0,
                    mana: Math.floor(Math.random()*(20 - 5)) +5,
                    intelligence: 0,
                    price: 2200,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_belt_4.png'),
                },
                {
                    id: 'arm_belt_5',
                    itemSlot: 'player_belt',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Giant's Belt",
                    description: 'Enchanted to give the wearer the strength of a giant',
                    value: '+1-5 strength, +10 mana',
                    attack: 0,
                    defense: 0,
                    strength: Math.floor(Math.random()*(5 - 1)) + 1,
                    life: 0,
                    mana: 10,
                    intelligence: 0,
                    price: 2800,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_belt_5.png'),
                },
                {
                    id: 'arm_belt_6',
                    itemSlot: 'player_belt',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Belt of Harmony",
                    description: 'Brings balance to your stats.  Aligns with your strongest stat.',
                    value: 'attack = defense = strength', //need to figure how to do this
                    attack: 0,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 4000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_belt_6.png'),
                },
                {
                    id: 'arm_leath_armor_1',
                    itemSlot: 'player_armor',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Basic Leather Armor',
                    description: 'Cheap, reliable, and sturdy.  A good armor for a new hunter.',
                    value: '+10 defense',
                    attack: 0,
                    defense: 10,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 200,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_armor_1.png'),
                },
                {
                    id: 'arm_leath_armor_2',
                    itemSlot: 'player_armor',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Quality Leather Armor',
                    description: "Lightweight, longwearing, and strong. You'll like this one.",
                    value: '+30 defense',
                    attack: 0,
                    defense: 30,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 800,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_armor_2.png'),
                },
                {
                    id: 'arm_leath_armor_3',
                    itemSlot: 'player_armor',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Dragonhide Armor',
                    description: 'A rare item.  Strong with intrinsic enchantments.  ',
                    value: '+50 defense, +10 attack, +10 mana ',
                    attack: 10,
                    defense: 50,
                    strength: 0,
                    life: 0,
                    mana: 10,
                    intelligence: 0,
                    price: 3500,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_armor_3.png'),
                },
                {
                    id: 'arm_robes_1',
                    itemSlot: 'player_armor',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Magic Robes',
                    description: 'Basic enchantments to help you in your quests.',
                    value: '+10 defense, +2 attack, +3 mana',
                    attack: 2,
                    defense: 10,
                    strength: 0,
                    life: 0,
                    mana: 3,
                    intelligence: 0,
                    price: 500,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_enchanted_robes_1.png'),
                },
                {
                    id: 'arm_robes_2',
                    itemSlot: 'player_armor',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Archmage's Robes",
                    description: 'The enchantments in these threads take a full year to weave.  Use wisely.',
                    value: '+20 defense, +5 attack, +5 strength, +3 life, +10 mana',
                    attack: 5,
                    defense: 20,
                    strength: 5,
                    life: 3,
                    mana: 10,
                    intelligence: 0,
                    price: 2500,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_enchanted_robes_2.png'),
                },
                {
                    id: 'arm_robes_3',
                    itemSlot: 'player_armor',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Dark Robes",
                    description: 'Wearing these will make you powerful, but at a cost.',
                    value: '+30 defense, +20 attack, +20 mana, -10 life',
                    attack: 20,
                    defense: 30,
                    strength: 0,
                    life: -10,
                    mana: 20,
                    intelligence: 0,
                    price: 4000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_enchanted_robes_3.png'),
                },
                {
                    id: 'arm_robes_4',
                    itemSlot: 'player_armor',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Runic Robes",
                    description: 'The magic in these is a bit chaotic, but they have potential for greatness.',
                    value: '+5-50 defense, +3-30 strength, +3-30 mana, -10 - +10 life',
                    attack: 0,
                    defense: Math.floor(Math.random()*(50 - 5)) + 5,
                    strength: Math.floor(Math.random()*(30 - 3)) + 3,
                    life: Math.floor(Math.random()*10)*(Math.round(Math.random()) ? 1 : -1),
                    mana: Math.floor(Math.random()*(30 - 3)) + 3,
                    intelligence: 0,
                    price: 5500,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_enchanted_robes_4.png'),
                },
                {
                    id: 'arm_leath_gauntlet_1',
                    itemSlot: 'player_gloves',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Leather Gauntlets',
                    description:"Just the thing to help you keep a strong grip on your sword.",
                    value: '+3 defense',
                    attack: 0,
                    defense: 3,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 100,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_gauntlets_1.png'),
                },
                {
                    id: 'arm_leath_gauntlet_2',
                    itemSlot: 'player_gloves',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Fingerless Leather Gauntlets',
                    description:"You might think they'd leave you more vulnerable, but actually no.",
                    value: '+10 defense',
                    attack: 0,
                    defense: 10,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 600,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_gauntlets_2.png'),
                },
                {
                    id: 'arm_leath_gauntlet_3',
                    itemSlot: 'player_gloves',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Werewolf Leather Gloves',
                    description:"Strong, flexible, and posessing a rare attack bonus.",
                    value: '+30 defense, +10 attack',
                    attack: 10,
                    defense: 30,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 1400,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_gauntlets_3.png'),
                },
                {
                    id: 'arm_leath_gauntlet_4',
                    itemSlot: 'player_gloves',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Chaos Gauntlets',
                    description:"Throws chaos into your opponent's schemes.  Not onto you.",
                    value: '+40 defense, +15 attack, +15 strength, +20 mana',
                    attack: 15,
                    defense: 40,
                    strength: 15,
                    life: 0,
                    mana: 20,
                    intelligence: 0,
                    price: 13000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_gauntlets_4.png'),
                },
                {
                    id: 'arm_vambraces_1',
                    itemSlot: 'player_vambraces',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Leather Vambraces',
                    description:"Pretty basic, but will reliably protect your arms.",
                    value: '+3 defense',
                    attack: 0,
                    defense: 3,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 200,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_vambraces_1.png'),
                },
                {
                    id: 'arm_vambraces_2',
                    itemSlot: 'player_vambraces',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Leonine Vambraces',
                    description:"Protective and fierce.  Just like the beast these are made from.",
                    value: '+9 defense, +2 attack',
                    attack: 2,
                    defense: 9,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 600,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_vambraces_2.png'),
                },
                {
                    id: 'arm_vambraces_3',
                    itemSlot: 'player_vambraces',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Valkyrie's Bracers",
                    description:"Blessed bracers that will be valuable to you on your quests.",
                    value: '+18 defense, +18 strength, +18 life, +18 mana',
                    attack: 0,
                    defense: 18,
                    strength: 18,
                    life: 18,
                    mana: 18,
                    intelligence: 0,
                    price: 3000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_vambraces_3.png'),
                },
                {
                    id: 'arm_vambraces_4',
                    itemSlot: 'player_vambraces',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Bossy Bracers",
                    description:"Adds 7 to all your stats.  Super useful for all hunter-bosses.",
                    value: '+7 attack, defense, strength, life, mana, and intelligence',
                    attack: 7,
                    defense: 7,
                    strength: 7,
                    life: 7,
                    mana: 7,
                    intelligence: 7,
                    price: 4007,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_vambraces_4.png'),
                },
                {
                    id: 'arm_leather_boots_1',
                    itemSlot: 'player_boots',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Sturdy Leather Boots',
                    description:'Hunting monsters with bad boots is a bad idea.  You need good footwear.',
                    value: '+3 defense and +2 strength',
                    attack: 0,
                    defense: 3,
                    strength: 2,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 150,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_boots_1.png'),
                },
                {
                    id: 'arm_leather_boots_2',
                    itemSlot: 'player_boots',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Quality Leather Boots',
                    description:'Well-balanced with extra waterproofing for those particularly soggy hunts.',
                    value: '+8 defense and +5 strength',
                    attack: 0,
                    defense: 8,
                    strength: 5,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 700,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_boots_2.png'),
                },
                {
                    id: 'arm_leather_boots_3',
                    itemSlot: 'player_boots',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Tall Leather Boots',
                    description:'In this case, the extra material means extra protection.',
                    value: '+15 defense and +5 strength',
                    attack: 0,
                    defense: 15,
                    strength: 5,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 1200,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_boots_3.png'),
                },
                {
                    id: 'arm_enchant_boots_1',
                    itemSlot: 'player_boots',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Enchanted Boots',
                    description: "Enchanted by a friendly Spirit, these are great if you're new to magic armor.",
                    value: '+1-5 defense, +1-10 health, +3 mana',
                    attack: 0,
                    defense: Math.floor(Math.random()*(5 - 1)) + 1,
                    strength: 0,
                    life: Math.floor(Math.random()*(10 - 1)) + 1,
                    mana: 3,
                    intelligence: 0,
                    price: 350,
                    imageSrc: require('../assets/images/village_armory/Armory_enchanted_boots_1.png'),
                },
                {
                    id: 'arm_enchant_boots_2',
                    itemSlot: 'player_boots',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Storyteller's Boots",
                    description: "Wearing these boots will give you lots of stories to tell, no doubt.",
                    value: '+5-15 defense, +1-20 strength, +5-20 health, +1-40 mana',
                    attack: 0,
                    defense: Math.floor(Math.random()*(15 - 5)) + 5,
                    strength: Math.floor(Math.random()*(20 - 1)) + 1,
                    life: Math.floor(Math.random()*(10 - 1)) + 1,
                    mana: Math.floor(Math.random()*(40 - 1)) + 1,
                    intelligence: 0,
                    price: 3500,
                    imageSrc: require('../assets/images/village_armory/Armory_enchanted_boots_2.png'),
                },
                {
                    id: 'arm_enchant_boots_3',
                    itemSlot: 'player_boots',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Purple Rain Boots",
                    description: "These boots are imbued with the most stable and dynamic spellwork I can find.",
                    value: '+10-50 defense, +5 strength, +10 life, +10 mana',
                    attack: 0,
                    defense: Math.floor(Math.random()*(50 - 10)) + 10,
                    strength: 5,
                    life: 10,
                    mana: 10,
                    intelligence: 0,
                    price: 5500,
                    imageSrc: require('../assets/images/village_armory/Armory_enchanted_boots_3.png'),
                },
                {
                    id: 'arm_horse_bag_1',
                    itemSlot: 'horse_bag',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Canvas Saddlebags",
                    description: "Basic canvas bags.  Waterproof with some carry capacity.",
                    value: 'allows your horse to carry 15% more items',
                    carryBonus: 1.5,
                    price: 400,
                    imageSrc: require('../assets/images/village_armory/Armory_bags_1.png'),
                },
                {
                    id: 'arm_horse_bag_2',
                    itemSlot: 'horse_bag',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Leather Saddlebags",
                    description: "These bags have large compartments that can hold plenty of loot.",
                    value: 'allows your horse to carry 25% more items',
                    carryBonus: 2.5,
                    price: 1500,
                    imageSrc: require('../assets/images/village_armory/Armory_bags_2.png'),
                },
                {
                    id: 'arm_horse_saddle_1',
                    itemSlot: 'horse_saddle',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Simple Leather Saddle",
                    description: "This saddle helps distribute the weight of items, so your horse can carry more.",
                    value: 'allows your horse to carry 10% more items',
                    carryBonus: 1,
                    price: 1000,
                    imageSrc: require('../assets/images/village_armory/Armory_saddle_1.png'),
                },
                {
                    id: 'arm_horse_saddle_2',
                    itemSlot: 'horse_saddle',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Fancy Leather Saddle",
                    description: "Not only does it look good, but it is sublimely well-balanced.",
                    value: 'allows your horse to carry 40% more items',
                    carryBonus: 4,
                    price: 3500,
                    imageSrc: require('../assets/images/village_armory/Armory_saddle_2.png'),
                },
            ],
            blacksmith: [ //note: will buy leathers, gems, scales, metals, metal-based armors
                {
                    id: 'smith_sword_1',
                    itemSlot: 'player_sword',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Basic Steel Sword',
                    description: 'A good, basic sword for hunters just starting out',
                    value: '+5 attack',
                    attack: 5,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 150,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_sword_1.png'),
                  },
                {
                    id: 'smith_sword_2',
                    itemSlot: 'player_sword',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Rapier',
                    description: 'A lightweight, fast, and sharp blade for slicing through your enemies.',
                    value: '+10 attack and +1 strength',
                    attack: 15,
                    defense: 0,
                    strength: 1,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 500,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_sword_2.png'),
                  },
                {
                    id: 'smith_sword_3',
                    itemSlot: 'player_sword',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Katana',
                    description: 'Agile, sharp-sharp, and strong.  Try not to cut yourself with this one.',
                    value: '+15 attack and +2 strength',
                    attack: 15,
                    defense: 0,
                    strength: 2,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 800,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_sword_3.png'),
                  },
                {
                    id: 'smith_sword_4',
                    itemSlot: 'player_sword',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Greatsword',
                    description: 'Heavyduty and powerful.  A solid weapon for both attack and defense.',
                    value: '+10 attack and +10 defense',
                    attack: 10,
                    defense: 10,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 1000,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_sword_4.png'),
                  },
                {
                    id: 'smith_sword_5',
                    itemSlot: 'player_sword',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Cutlass',
                    description: 'A sturdy and well-balanced sword.  Also comes with built-in pirate cred.',
                    value: '+20 attack',
                    attack: 20,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 1100,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_sword_5.png'),
                  },
                {
                    id: 'smith_sword_6',
                    itemSlot: 'player_sword',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Falchion',
                    description: 'A heavy duty sword that will bisect your enemies with ease.',
                    value: '+15 attack and +5 strength',
                    attack: 15,
                    defense: 0,
                    strength: 5,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 1350,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_sword_6.png'),
                  },
                {
                    id: 'smith_sword_7',
                    itemSlot: 'player_sword',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Scimitar',
                    description: 'Lightweight, fast, and strong. A fantastic sword for any enthusiast.',
                    value: '+20 attack, +10 defense, and +5 strength',
                    attack: 20,
                    defense: 10,
                    strength: 5,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 1800,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_sword_7.png'),
                  },
                {
                    id: 'smith_sword_8',
                    itemSlot: 'player_sword',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Iced Blade',
                    description: 'An enchanted blade with a stable core of magical ice.',
                    value: '+15 attack, +15 defense, +4 mana',
                    attack: 15,
                    defense: 15,
                    strength: 0,
                    life: 0,
                    mana: 4,
                    intelligence: 0,
                    price: 2200,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_sword_8.png'),
                  },
                {
                    id: 'smith_sword_9',
                    itemSlot: 'player_sword',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Fiery Blade',
                    description: 'An volatile blade made from solidified phoenix flame.',
                    value: '+1-30 attack, +1-15 strength, +1-20 life, +1-20 mana',
                    attack: Math.floor(Math.random()*(30 - 1)) + 1,
                    defense: 0,
                    strength: Math.floor(Math.random()*(15 - 1)) + 1,
                    life: Math.floor(Math.random()*(20 - 1)) + 1,
                    mana: Math.floor(Math.random()*(20 - 1)) + 1,
                    intelligence: 0,
                    price: 2800,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_sword_9.png'),
                  },
                {
                    id: 'smith_sword_10',
                    itemSlot: 'player_sword',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Earthen Blade',
                    description: 'An stabilized enchanted blade made from sacred earth.',
                    value: '+20 attack, +10 defense, +5-25 strength, +10 mana',
                    attack: 20,
                    defense: 10,
                    strength: Math.floor(Math.random()*(25 - 5)) + 5,
                    life: 0,
                    mana: 10,
                    intelligence: 0,
                    price: 3300,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_sword_10.png'),
                  },
                {
                    id: 'smith_sword_11',
                    itemSlot: 'player_sword',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Aerie Blade',
                    description: 'The fastest sword you can find in any market anywhere.',
                    value: '+25-60 attack, +2 mana',
                    attack: Math.floor(Math.random()*(60 - 25)) + 25,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: 2,
                    intelligence: 0,
                    price: 5000,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_sword_11.png'),
                  },
                {
                    id: 'smith_sword_12',
                    itemSlot: 'player_sword',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Fell Sword',
                    description: 'Very powerful, but at a cost.  Are you willing to risk it?',
                    value: '+20-40 attack, +20-40 defense, +10-20 strength, -5-30 life, -1-10 mana',
                    attack: Math.floor(Math.random()*(40 - 20)) + 20,
                    defense: Math.floor(Math.random()*(40 - 20)) + 20,
                    strength: Math.floor(Math.random()*(20 - 10)) + 10,
                    life: (Math.floor(Math.random()*(30 - 5)) + 5)*-1,
                    mana: (Math.floor(Math.random()*(10 - 1)) + 1)*-1,
                    intelligence: 0,
                    price: 6000,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_sword_12.png'),
                  },
                {
                    id: 'smith_sword_13',
                    itemSlot: 'player_sword',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Blessed Sword',
                    description: 'Raises everything between 10 and 25 points',
                    value: '+10-25 to attack, defense, strength, life, mana, and intelligence',
                    attack: Math.floor(Math.random()*(25 - 10)) + 10,
                    defense: Math.floor(Math.random()*(25 - 10)) + 10,
                    strength: Math.floor(Math.random()*(25 - 10)) + 10,
                    life: Math.floor(Math.random()*(25 - 10)) + 10,
                    mana: Math.floor(Math.random()*(25 - 10)) + 10,
                    intelligence: Math.floor(Math.random()*(25 - 10)) + 10,
                    price: 13000,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_sword_13.png'),
                  },
                  {
                    id: 'smith_shield_1',
                    itemSlot: 'player_shield', 
                    itemUse: 'null',
                    itemShop: 'Blacksmith',                   
                    name: 'Basic Wooden Shield',
                    description:"A good shield to start with.  But maybe avoid fire-beasts.",
                    value: '+3 defense',
                    attack: 0,
                    defense: 3,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 100,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_shield_1.png'),
                  },
                  {
                    id: 'smith_shield_2',
                    itemSlot: 'player_shield', 
                    itemUse: 'null',
                    itemShop: 'Blacksmith',                   
                    name: 'Kite Shield',
                    description:"Offers great defense coverage.  But it's heavy.",
                    value: '+15 defense, -2 strength',
                    attack: 0,
                    defense: 15,
                    strength: -2,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 500,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_shield_2.png'),
                  },
                  {
                    id: 'smith_shield_3',
                    itemSlot: 'player_shield', 
                    itemUse: 'null',
                    itemShop: 'Blacksmith',                   
                    name: 'Buckler Shield',
                    description:"Lightweight and strong.  Gives you the defensive flexibility you need.",
                    value: '+17 defense',
                    attack: 0,
                    defense: 17,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 800,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_shield_3.png'),
                  },
                  {
                    id: 'smith_shield_4',
                    itemSlot: 'player_shield', 
                    itemUse: 'null',
                    itemShop: 'Blacksmith',                   
                    name: 'Heater Shield',
                    description:"Offers coverage like the kite shield, but an enchantment keeps the weight light.",
                    value: '+25 defense, +1-5 life',
                    attack: 0,
                    defense: 25,
                    strength: 0,
                    life: Math.floor(Math.random()*(5 - 1))+ 1,
                    mana: 0,
                    intelligence: 0,
                    price: 1600,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_shield_4.png'),
                  },
                  {
                    id: 'smith_shield_5',
                    itemSlot: 'player_shield', 
                    itemUse: 'null',
                    itemShop: 'Blacksmith',                   
                    name: 'Stone Shield',
                    description:"Powerful magic feeds this one. Great defense, with a bit of a cost to keep it.",
                    value: '+55 defense, -15 mana',
                    attack: 0,
                    defense: 55,
                    strength: 0,
                    life: 0,
                    mana: -15,
                    intelligence: 0,
                    price: 5500,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_shield_5.png'),
                  },
                  {
                    id: 'smith_shield_6',
                    itemSlot: 'player_shield', 
                    itemUse: 'null',
                    itemShop: 'Blacksmith',                   
                    name: 'Woodlands Shield',
                    description:"A well-balanced, blessed shield made from wood from a sacred forest.",
                    value: '+28 defense, +14 strength, +14 life, +14 mana',
                    attack: 0,
                    defense: 28,
                    strength: 14,
                    life: 14,
                    mana: 14,
                    intelligence: 0,
                    price: 7777,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_shield_6.png'),
                  },
                  {
                    id: 'smith_helm_1',
                    itemSlot: 'player_helm',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Metal Helmet',
                    description:"Some basic head protection.  You're going to want it.",
                    value: '+3 defense',
                    attack: 0,
                    defense: 3,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 150,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_helmet_1.png'),                    
                  },
                  {
                    id: 'smith_helm_2',
                    itemSlot: 'player_helm',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Steel-faced Helm',
                    description:"Offers greater protection to your beautiful face.",
                    value: '+10 defense',
                    attack: 0,
                    defense: 10,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 500,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_helmet_2.png'),                    
                  },
                  {
                    id: 'smith_helm_3',
                    itemSlot: 'player_helm',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Full Helmet',
                    description:"Protects both the front AND the back of your head, while still letting you see.",
                    value: '+20 defense',
                    attack: 0,
                    defense: 20,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 1100,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_helmet_3.png'),                    
                  },
                  {
                    id: 'smith_helm_4',
                    itemSlot: 'player_helm',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Chained Hood',
                    description:"Protects everything from the neck up.  Lightweight, cooling, and flexible.",
                    value: '+40 defense',
                    attack: 0,
                    defense: 40,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 2000,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_helmet_4.png'),                    
                  },
                  {
                    id: 'smith_armor_1',
                    itemSlot: 'player_armor',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Studded Leather Armor',
                    description:"Offers good protection for most of your vital bits.",
                    value: '+20 defense',
                    attack: 0,
                    defense: 20,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 800,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_armor_1.png'),                    
                  },
                  {
                    id: 'smith_armor_2',
                    itemSlot: 'player_armor',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Chainmail Armor',
                    description:"Strong, flexible, but heavy. A good value if you don't mind the cost.",
                    value: '+30 defense, +3 attack, -5 strength',
                    attack: 3,
                    defense: 30,
                    strength: -5,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 1200,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_armor_2.png'),                    
                  },
                  {
                    id: 'smith_armor_3',
                    itemSlot: 'player_armor',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Plate mail Armor',
                    description:"Very strong, surprisingly lightweight, but inflexible.",
                    value: '+35 defense, -5 attack',
                    attack: -5,
                    defense: 35,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 2500,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_armor_3.png'),                    
                  },
                  {
                    id: 'smith_armor_4',
                    itemSlot: 'player_armor',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Karkadaan Leather Armor',
                    description:"Enchanted armor that will improve both defense and strength.",
                    value: '+ 15-40 defense, +10-20 strength',
                    attack: 0,
                    defense: Math.floor(Math.random()*(40 - 15)) + 15,
                    strength: Math.floor(Math.random(20 - 10)) + 10,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 4000,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_armor_4.png'),                    
                  },
                  {
                    id: 'smith_armor_5',
                    itemSlot: 'player_armor',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Mithril Armor',
                    description:"This rare, magic metal is famous for a reason.  Try it out.",
                    value: '+20-30 defense, life, and mana',
                    attack: 0,
                    defense: Math.floor(Math.random()*(30 - 20)) + 20,
                    strength: 0,
                    life: Math.floor(Math.random()*(30 - 20)) + 20,
                    mana: Math.floor(Math.random()*(30 - 20)) + 20,
                    intelligence: 0,
                    price: 9000,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_armor_5.png'),                    
                  },
                  {
                    id: 'smith_armor_6',
                    itemSlot: 'player_armor',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: "Warrior's Plate Mail",
                    description:"Magic armor enchanted by a famous, now-retired, warrior wizard.",
                    value: '+30 defense, +10-20 attack, +10-20 strength, +15 mana',
                    attack: Math.floor(Math.random()*(20 - 10))+ 10,
                    defense: 30,
                    strength: Math.floor(Math.random(20 - 10)) + 10,
                    life: 0,
                    mana: 15,
                    intelligence: 0,
                    price: 11000,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_armor_6.png'),                    
                  },
                  {
                    id: 'smith_vambrace_1',
                    itemSlot: 'player_vambraces',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: "Steel Vambraces",
                    description:"Basic, simple, reliable braces to protect your forearms from attack.",
                    value: '+3 defense',
                    attack: 0,
                    defense: 3,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 110,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_bracer_1.png'),                    
                  },
                  {
                    id: 'smith_vambrace_2',
                    itemSlot: 'player_vambraces',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: "Hinged Vambraces",
                    description:"More advanced vambraces that will protect more of your arm.",
                    value: '+9 defense',
                    attack: 0,
                    defense: 9,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 450,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_bracer_2.png'),                    
                  },
                  {
                    id: 'smith_vambrace_3',
                    itemSlot: 'player_vambraces',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: "Articulated Vambraces",
                    description:"Jointed, articulated assembly allows for full arm protection along with greater flexibility.",
                    value: '+21 defense',
                    attack: 0,
                    defense: 21,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 1100,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_bracer_3.png'),                    
                  },
                  {
                    id: 'smith_vambrace_4',
                    itemSlot: 'player_vambraces',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: "Filigre Vambraces",
                    description:"Forged using a secret elfin technique, these are very powerful.",
                    value: '+26 defense +14 attack',
                    attack: 14,
                    defense: 26,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 3400,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_bracer_4.png'),                    
                  },
                  {
                    id: 'smith_boots_1',
                    itemSlot: 'player_boots',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: "Iron Boots",
                    description:"Not the most comfortable things in the world, but nothing will get through them.",
                    value: '+20 defense, -2 strength',
                    attack: 0,
                    defense: 20,
                    strength: -2,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 400,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_boots_1.png'),                    
                  },
                  {
                    id: 'smith_boots_2',
                    itemSlot: 'player_boots',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: "Steel-toed Boots",
                    description:"Lighter than iron, but loud.  No sneaking up on anyone with these.",
                    value: '+30 defense, -2 attack',
                    attack: -2,
                    defense: 20,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 900,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_boots_2.png'),                    
                  },
                  {
                    id: 'smith_boots_3',
                    itemSlot: 'player_boots',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: "Plated Boots",
                    description:"Far more comfortable than they look.  Give them a try.",
                    value: '+30 defense, +5 attack, +3 strength',
                    attack: 5,
                    defense: 30,
                    strength: 3,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 1600,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_boots_3.png'),                    
                  },                  
                  {
                    id: 'smith_horse_1',
                    itemSlot: 'horse_shoes',  
                    itemUse: 'null', 
                    itemShop: 'Blacksmith',                 
                    name: 'Horseshoes',
                    description: "Everyone feels better with proper footware, horses included",
                    value: 'allows your horse to carry 10% more items',
                    carryBonus: 1,
                    price: 200,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_horseshoes_1.png'),
                  },
                  {
                    id: 'smith_horse_2',
                    itemSlot: 'horse_shoes',  
                    itemUse: 'null', 
                    itemShop: 'Blacksmith',                 
                    name: 'Elfin Horseshoes',
                    description: "Lightweight and energizing.  Your horse will love them.",
                    value: 'allows your horse to carry 25% more items',
                    carryBonus: 2.5,
                    price: 1200,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_horseshoes_2.png'),
                  },
                  {
                    id: 'smith_horse_3',
                    itemSlot: 'horse_shoes',  
                    itemUse: 'null', 
                    itemShop: 'Blacksmith',                 
                    name: 'Golden Horseshoes',
                    description: "Blessed shoes that will make your horse stronger than ever.",
                    value: 'allows your horse to carry 40% more items',
                    carryBonus: 4,
                    price: 3600,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_horseshoes_3.png'),
                  },
            ],
            oddities: [
                {
                    id: 'odd_ring_1',
                    itemSlot: 'player_ring',
                    itemUse: 'null',
                    itemShop: 'Oddities',
                    name: 'Enchanted Ring of Vigor',
                    description: 'Made by elves.  Good on the battlefield, and in the bedroom!',
                    value: '+4 attack',
                    attack: 4,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    price: 500,
                    imageSrc: require('../assets/images/village_oddities/Oddities_enchanted_ring_1.png'),
                  },
                  {
                    id: 'odd_talisman_1',
                    itemSlot: 'null',
                    itemUse: 'null',
                    itemShop: 'Oddities',
                    name: 'Raven Skull',
                    description:"Useful for potions and spellwork.",
                    value: 'Potency results may vary',
                    price: 50,
                    imageSrc: require('../assets/images/village_oddities/Oddities_talisman_1.png'),
                  },
                  {
                    id: 'odd_gloves_1',
                    itemSlot: 'player_gloves',
                    itemUse: 'null',
                    itemShop: 'Oddities',
                    name: 'Mysterious Leather Gloves',
                    description:"No telling what they do - but they're magic!",
                    value: '???',
                    attack: 0,
                    defense: 0,
                    strength: 0,
                    life: 10,
                    price: 750,
                    imageSrc: require('../assets/images/village_oddities/Oddities_enchanted_gloves_1.png'),
                  },
                  {
                    id: 'odd_herb_1',
                    itemSlot: 'null',
                    itemUse: 'null',
                    itemShop: 'Oddities',
                    name: "Mountain's Bane",
                    description: "A very rare herb of very potent magic",
                    value: 'Results vary by application',
                    price: 3000,
                    imageSrc: require('../assets/images/village_oddities/Oddities_herb_1.png'),
                  },
            ],

        }),
        actions: {
            getUniqueID() {  //trying to get unique ids for items in shop ... still not working.  executes once when store is created, not each time an item is sold
                this.id = (this.id + Math.ceil(Math.random()*1000000));
            },
            
        }
    })