import { defineStore } from 'pinia'

export const useShopStore =
    defineStore({
        id: 'shops',
        state: () => ({
            playerId: 'Player One',
            playerLevel: 1,
            apothecary: [ // note: will buy herbs, potions, and meats 
                {
                    id: 'apo_health_1',
                    // id: Math.floor(Math.random() * 10000)
                    // note: this works to generate a random#, but it only does it once.  how to generate a new # with each sale?
                    itemSlot: 'null',
                    itemUse: 'healing',
                    itemShop: 'Apothecary',
                    name: 'Basic Healing Draught',                    
                    description: 'A simple brew that will perk you up a bit.',
                    value: '+10 health',
                    attack: 0,
                    defense: 0,
                    strength: 0,
                    life: 10,
                    mana: 0, 
                    intelligence: 0,
                    price: 50,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_healing_1.png'),                    
                },
                {
                    id: 'apo_health_2',
                    itemSlot: 'null',
                    itemUse: 'healing',
                    itemShop: 'Apothecary',
                    name: 'Concentrated Healing Draught',                    
                    description: "A strong spirit that will reinvigorate you if you're feeling down.",
                    value: '+25 health',
                    attack: 0,
                    defense: 0,
                    strength: 0,
                    life: 25,
                    mana: 0, 
                    intelligence: 0,
                    price: 150,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_healing_2.png'),                    
                },
                {
                    id: 'apo_health_3',
                    itemSlot: 'null',
                    itemUse: 'healing',
                    itemShop: 'Apothecary',
                    name: 'Greater Healing Draught',                    
                    description: 'A potent cordial that will get you feeling much better',
                    value: '+50 health',
                    attack: 0,
                    defense: 0,
                    strength: 0,
                    life: 50,
                    mana: 0, 
                    intelligence: 0,
                    price: 300,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_healing_3.png'),                    
                },
                {
                    id: 'apo_health_4',
                    itemSlot: 'null',
                    itemUse: 'healing',
                    itemShop: 'Apothecary',
                    name: 'Blessed Healing Draught',                    
                    description: 'The strongest healing brew I make.  For most adventurers, it offers full healing.',
                    value: '+200 health',
                    attack: 0,
                    defense: 0,
                    strength: 0,
                    life: 200,
                    mana: 0, 
                    intelligence: 0,
                    price: 1000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_healing_4.png'),                    
                },
                {
                    id: 'apo_attack_1',
                    itemSlot: 'null',
                    itemUse: 'attacking',
                    itesmShop: 'Apothecary',
                    name: 'Energizing Tincure',
                    description:"Rub this in and you'll instantly feel the effects. Lasts for one battle",
                    value: '+5 attack',
                    attack: 5,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 500,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_attack_1.png'),                    
                },
                {
                    id: 'apo_attack_2',
                    itemSlot: 'null',
                    itemUse: 'attacking',
                    itesmShop: 'Apothecary',
                    name: 'Tincure of Motivation',
                    description:"Apply this potion and get what you need to succeed.  Lasts for one battle.",
                    value: '+10 attack',
                    attack: 10,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 1000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_attack_2.png'),                    
                },
                {
                    id: 'apo_attack_3',
                    itemSlot: 'null',
                    itemUse: 'attacking',
                    itesmShop: 'Apothecary',
                    name: 'Tincure of Inspiration',
                    description:"When applied, you'll aspire to greatness. Lasts for one battle",
                    value: '+25 attack',
                    attack: 25,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 1500,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_attack_3.png'),                    
                },
                {
                    id: 'apo_attack_4',
                    itemSlot: 'null',
                    itemUse: 'attack',
                    itesmShop: 'Apothecary',
                    name: 'Tincure of Vigor',
                    description:"Slather this on to gain a new energy toward life.  Effects are permanent!",
                    value: '+1 attack',
                    attack: 1,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 2000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_attack_4.png'),                    
                },
                {
                    id: 'apo_attack_5',
                    itemSlot: 'null',
                    itemUse: 'attack',
                    itesmShop: 'Apothecary',
                    name: 'Tincure of Ruthlessness',
                    description:"Douse yourself with this and see your enemies flee.  Effects are permanent!",
                    value: '+5 attack',
                    attack: 5,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 5000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_attack_5.png'),                    
                },
                {
                    id: 'apo_defense_1',
                    itemSlot: 'null',
                    itemUse: 'defending',
                    itemShop: 'Apothecary',
                    name: 'Small Shot Potion',
                    description:'Down this potion to gain a quick defense bonus.  Lasts for one battle.',
                    value: '+5 defense',
                    attack: 0,
                    defense: 5,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 350,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_defense_1.png'),                    
                },
                {
                    id: 'apo_defense_2',
                    itemSlot: 'null',
                    itemUse: 'defending',
                    itemShop: 'Apothecary',
                    name: "Defender's Doubleshot",
                    description:'Drink this to gain a good bit of defense power.  Lasts for one battle.',
                    value: '+15 defense',
                    attack: 0,
                    defense: 15,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 800,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_defense_2.png'),                    
                },
                {
                    id: 'apo_defense_3',
                    itemSlot: 'null',
                    itemUse: 'defense',
                    itemShop: 'Apothecary',
                    name: "Defender's Potion",
                    description:'Sip on this potion and gain a permanent defense bonus.',
                    value: '+1 defense',
                    attack: 0,
                    defense: 1,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 2000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_defense_3.png'),                    
                },
                {
                    id: 'apo_defense_4',
                    itemSlot: 'null',
                    itemUse: 'defense',
                    itemShop: 'Apothecary',
                    name: "Shell of Protection",
                    description:'Savor this potion.  The effects are permanent!',
                    value: '+5 defense',
                    attack: 0,
                    defense: 5,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 4000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_defense_4.png'),                    
                },
                {
                    id: 'apo_strength_1',
                    itemSlot: 'null',
                    itemUse: 'strengthening',
                    itemShop: 'Apothecary',
                    name: 'Strength Potion',
                    description:'Simple enough.  Drink this; get stronger.  Until you win your next battle, anyway.',
                    value: '+3 strength',
                    attack: 0,
                    defense: 0,
                    strength: 3,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 300,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_strength_1.png'),                    
                },
                {
                    id: 'apo_strength_2',
                    itemSlot: 'null',
                    itemUse: 'strengthening',
                    itemShop: 'Apothecary',
                    name: 'Hardiness Potion',
                    description:'Drink this and you can handle whatever comes!  Lasts for one battle.',
                    value: '+8 strength',
                    attack: 0,
                    defense: 0,
                    strength: 8,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 800,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_strength_2.png'),                    
                },
                {
                    id: 'apo_strength_3',
                    itemSlot: 'null',
                    itemUse: 'strength',
                    itemShop: 'Apothecary',
                    name: 'Potion of Brawn',
                    description:'This potion will permanently bulk you up!',
                    value: '+1 strength',
                    attack: 0,
                    defense: 0,
                    strength: 1,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 1300,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_strength_3.png'),                    
                },
                {
                    id: 'apo_strength_4',
                    itemSlot: 'null',
                    itemUse: 'strength',
                    itemShop: 'Apothecary',
                    name: 'Potion of Durability',
                    description:'Give it a try and see how much harder you can hit!  Effects are permanent.',
                    value: '+5 strength',
                    attack: 0,
                    defense: 0,
                    strength: 5,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 2000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_strength_4.png'),                    
                },
                {
                    id: 'apo_soup_1',
                    itemSlot: 'null',
                    itemUse: 'multi',
                    itemShop: 'Apothecary',
                    name: 'Bone Broth Soup',
                    description: "I know how it looks.  Just give it a try - I think you'll like it!",
                    value: '+3 health, +1 strength, fully charges mana',
                    attack: 0,
                    defense: 0,
                    strength: 1,
                    life: 3,
                    mana: 1,
                    intelligence: 0,
                    price: 2000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_soup_1.png'),                    
                },
                {
                    id: 'apo_soup_2',
                    itemSlot: 'null',
                    itemUse: 'multi',
                    itemShop: 'Apothecary',
                    name: 'Vegetable Soup',
                    description: "Full of vitamins and fiber - it's just what you need!",
                    value: '+3 health, +3 attack, fully charges mana',
                    attack: 3,
                    defense: 0,
                    strength: 0,
                    life: 3,
                    mana: 1,
                    intelligence: 0,
                    price: 4000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_soup_2.png'),                    
                },
                {
                    id: 'apo_soup_3',
                    itemSlot: 'null',
                    itemUse: 'multi',
                    itemShop: 'Apothecary',
                    name: 'Cream of Mushroom Soup',
                    description: "Made from freshly-foraged mushroom spirits, it'll perk you right up!",
                    value: '+3 health, +3 attack, +3 defense, fully charges mana',
                    attack: 3,
                    defense: 3,
                    strength: 0,
                    life: 3,
                    mana: 1,
                    intelligence: 0,
                    price: 6500,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_soup_3.png'),                    
                },
                {
                    id: 'apo_soup_4',
                    itemSlot: 'null',
                    itemUse: 'multi',
                    itemShop: 'Apothecary',
                    name: 'Chicken Noodle Soup',
                    description: "A classic for a reason - it's practically the perfect soup!",
                    value: '+8 health, +3 strength, +5 defense, fully charges mana',
                    attack: 0,
                    defense: 5,
                    strength: 3,
                    life: 8,
                    mana: 1,
                    intelligence: 0,
                    price: 8000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_soup_4.png'),                    
                },
                {
                    id: 'apo_soup_5',
                    itemSlot: 'null',
                    itemUse: 'multi',
                    itemShop: 'Apothecary',
                    name: 'Beef Stew',
                    description: "Hearty and filling - it'll warm you down to the soul!",
                    value: '+8 health, +3 strength, +5 attack, fully charges mana',
                    attack: 5,
                    defense: 0,
                    strength: 3,
                    life: 8,
                    mana: 1,
                    intelligence: 0,
                    price: 8000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_soup_5.png'),                    
                },
                {
                    id: 'apo_soup_6',
                    itemSlot: 'null',
                    itemUse: 'multi',
                    itemShop: 'Apothecary',
                    name: 'Spicy Curry Soup',
                    description: "The strongest, spiciest, wildest soup I can make!  Effects may vary.",
                    value: '+5-15 health, +1-5 attack, +1-5 defense, +1-5 strength, and fully charges mana',
                    attack: Math.floor(Math.random()*(10 - 1)) +1,
                    defense: Math.floor(Math.random()*(10 - 1)) + 1,
                    strength: Math.floor(Math.random()*(10 - 1)) + 1,
                    life: Math.floor(Math.random()*(15 - 5)) + 5,
                    mana: 1,
                    intelligence: 0,
                    price: 12000,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_apothecary/Apothecary_soup_6.png'),                    
                },
            ],
            armory: [  // note: will buy leathers, gems, scales, cloth-based items
                {
                    id: 'arm_belt_1',
                    itemSlot: 'player_belt',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Quicksilver Belt',
                    description: 'Enchanted belt that will improve your attacks.',
                    value: '+5-15 attack, +3-10 mana',
                    attack: Math.floor(Math.random()*(15 - 5)) +5,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: Math.floor(Math.random()*(10 - 3)) +3,
                    intelligence: 0,
                    price: 200,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_armor_1.png'),
                },
                {
                    id: 'arm_belt_2',
                    itemSlot: 'player_belt',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Belt of Lightening',
                    description: 'Enchanted belt made from captured lightning.',
                    value: '+10-30 attack, +5-20 mana',
                    attack: Math.floor(Math.random()*(30 - 10)) +10,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: Math.floor(Math.random()*(20 - 5)) +5,
                    intelligence: 0,
                    price: 200,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_armor_1.png'),
                },
                {
                    id: 'arm_belt_3',
                    itemSlot: 'player_belt',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Grey Wizard's Belt",
                    description: 'Enchanted using a spell from the great Grey Wizard themself.',
                    value: '+5-15 defense, +3-10 mana',
                    attack: 0,
                    defense: Math.floor(Math.random()*(15 - 5)) +5,
                    strength: 0,
                    life: 0,
                    mana: Math.floor(Math.random()*(10 - 3)) +3,
                    intelligence: 0,
                    price: 200,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_armor_1.png'),
                },
                {
                    id: 'arm_belt_4',
                    itemSlot: 'player_belt',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Templar's Belt",
                    description: 'Imported from the blessed Templar Monastery.',
                    value: '+10-30 defense, +5-20 mana',
                    attack: 0,
                    defense: Math.floor(Math.random()*(30 - 10)) +10,
                    strength: 0,
                    life: 0,
                    mana: Math.floor(Math.random()*(20 - 5)) +5,
                    intelligence: 0,
                    price: 200,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_armor_1.png'),
                },
                {
                    id: 'arm_belt_5',
                    itemSlot: 'player_belt',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Giant's Belt",
                    description: 'Enchanted to give the wearer the strength of a giant',
                    value: '+1-5 strength, +10 mana',
                    attack: 0,
                    defense: 0,
                    strength: Math.floor(Math.random()*(5 - 1)) + 1,
                    life: 0,
                    mana: 10,
                    intelligence: 0,
                    price: 200,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_armor_1.png'),
                },
                {
                    id: 'arm_belt_6',
                    itemSlot: 'player_belt',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: "Belt of Harmony",
                    description: 'Brings balance to your stats',
                    value: 'attack = defense = strength', //need to figure how to do this
                    attack: 0,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    mana: 0,
                    intelligence: 0,
                    price: 200,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_armor_1.png'),
                },
                {
                    id: 'arm_leath_armor_1',
                    itemSlot: 'player_armor',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Basic Leather Armor',
                    description: 'Cheap, reliable, and sturdy',
                    value: '+10 defense',
                    attack: 0,
                    defense: 10,
                    strength: 0,
                    life: 0,
                    price: 200,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_armor_1.png'),
                },
                {
                    id: 'arm_leath_gauntlet_1',
                    itemSlot: 'player_gloves',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Leather Gauntlets',
                    description:"Just the thing to help you keep a strong grip on your sword.",
                    value: '+3 defense',
                    attack: 0,
                    defense: 3,
                    strength: 0,
                    life: 0,
                    price: 100,
                    unlocksAt: 2,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_gauntlets_1.png'),
                },
                {
                    id: 'arm_leather_boots_1',
                    itemSlot: 'player_boots',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Sturdy Leather Boots',
                    description:'Hunting monsters with bad boots is a bad idea.  You need good footwear.',
                    value: '+3 defense and +2 strength',
                    attack: 0,
                    defense: 3,
                    strength: 2,
                    life: 0,
                    price: 150,
                    unlocksAt: 1,
                    imageSrc: require('../assets/images/village_armory/Armory_leather_boots_1.png'),
                },
                {
                    id: 'arm_enchant_boots_1',
                    itemSlot: 'player_boots',
                    itemUse: 'null',
                    itemShop: 'Armory',
                    name: 'Enchanted Boots',
                    description: "A gift from a friendly 'Shroom Spirit, these are great if you're considering adding magic items to your armor",
                    value: '+1-5 defense, and poison resistance, and occasional +1-5 health',
                    attack: 0,
                    defense: 3,
                    strength: 0,
                    life: 5,
                    price: 350,
                    imageSrc: require('../assets/images/village_armory/Armory_enchanted_boots_1.png'),
                },
            ],
            blacksmith: [
                {
                    id: 'smith_sword_1',
                    itemSlot: 'player_sword',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Basic Steel Sword',
                    description: 'A good sword to start out with',
                    value: '+5 attack',
                    attack: 5,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    price: 150,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_sword_1.png'),
                  },
                  {
                    id: 'smith_helm_1',
                    itemSlot: 'player_helm',
                    itemUse: 'null',
                    itemShop: 'Blacksmith',
                    name: 'Metal Helmet',
                    description:"Some basic head protection.  You're going to want it.",
                    value: '+3 defense',
                    attack: 0,
                    defense: 3,
                    strength: 0,
                    life: 0,
                    price: 150,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_helmet_1.png'),                    
                  },
                  {
                    id: 'smith_shield_1',
                    itemSlot: 'player_shield', 
                    itemUse: 'null',
                    itemShop: 'Blacksmith',                   
                    name: 'Basic Wooden Shield',
                    description:"Won't help much against fire-based monsters, but useful against pretty much everything else.",
                    value: '+3 defense',
                    attack: 0,
                    defense: 3,
                    strength: 0,
                    life: 0,
                    price: 100,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_shield_1.png'),
                  },
                  {
                    id: 'smith_misc_1',
                    itemSlot: 'horse_shoes',  
                    itemUse: 'null', 
                    itemShop: 'Blacksmith',                 
                    name: 'Horseshoes',
                    description: "Everyone feels better with proper footware, horses included",
                    value: 'allows your horse to carry 10% more items',
                    carryBonus: 1,
                    price: 200,
                    imageSrc: require('../assets/images/village_blacksmith/Blacksmith_horseshoes_1.png'),
                  },
            ],
            oddities: [
                {
                    id: 'odd_ring_1',
                    itemSlot: 'player_ring',
                    itemUse: 'null',
                    itemShop: 'Oddities',
                    name: 'Enchanted Ring of Vigor',
                    description: 'Made by elves.  Good on the battlefield, and in the bedroom!',
                    value: '+4 attack',
                    attack: 4,
                    defense: 0,
                    strength: 0,
                    life: 0,
                    price: 500,
                    imageSrc: require('../assets/images/village_oddities/Oddities_enchanted_ring_1.png'),
                  },
                  {
                    id: 'odd_skull_1',
                    itemSlot: 'null',
                    itemUse: 'null',
                    itemShop: 'Oddities',
                    name: 'Raven Skull',
                    description:"Useful for potions and spellwork.",
                    value: 'Potency results may vary',
                    price: 50,
                    imageSrc: require('../assets/images/village_oddities/Oddities_skull_1.png'),
                  },
                  {
                    id: 'odd_gloves_1',
                    itemSlot: 'player_gloves',
                    itemUse: 'null',
                    itemShop: 'Oddities',
                    name: 'Mysterious Leather Gloves',
                    description:"No telling what they do - but they're magic!",
                    value: '???',
                    attack: 0,
                    defense: 0,
                    strength: 0,
                    life: 10,
                    price: 750,
                    imageSrc: require('../assets/images/village_oddities/Oddities_enchanted_gloves_1.png'),
                  },
                  {
                    id: 'odd_herb_1',
                    itemSlot: 'null',
                    itemUse: 'null',
                    itemShop: 'Oddities',
                    name: "Mountain's Bane",
                    description: "A very rare herb of very potent magic",
                    value: 'Results vary by application',
                    price: 3000,
                    imageSrc: require('../assets/images/village_oddities/Oddities_herb_1.png'),
                  },
            ],

        }),
        actions: {
            getUniqueID() {  //trying to get unique ids for items in shop ... still not working.  executes once when store is created, not each time an item is sold
                this.id = (this.id + Math.ceil(Math.random()*1000000));
            },
            
        }
    })